### ISSUE TITLE
Struggling to visualize Convolutions

### ISSUE THREAD

**Issue by ducttrn** [gc625/DLCV#1]
Hi, after we went through CNNs for workshop 2, I'm still a little unclear about why the kernels are three-dimensional when the input image is 2D. Thanks!

**Comment by gc625** [comment]
Hey Bill, this is because a color image with dimensions $N\times N$ is actually a $N\times N\times 3$ tensor. The $3$ represents the three color channels (red, green blue). Since the kernel is multiplied element-wise with the image, it needs to have a dimension of $3$ as well. 

In the general case for an input with dimensions $N\times N \times C$, the kernel can to have a dimension of $K\times K \times C$. Typically, $K=3$. 

Here's an animation from the youtube channel Animated AI  which illustrates this process quite clearly. 

https://user-images.githubusercontent.com/29677319/205172607-2426076c-62e0-4c82-b68d-de7b52bc6396.mp4

let me know if you have any other questions!

**Comment by ducttrn** [comment]
I got it, thank you for your thoughtful and detailed response!
